/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData btn_back_arrow_bold = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_order_status = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_notice = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_fixseat_1 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_time = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_timepack = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_notice = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_ticket = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_x = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_checkbox_check_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_money = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_period = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_point = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_seat_locker_copy = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_setting = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_timepack = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_timepack_charge_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_collapse = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_search_copy_2 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_hart_2_copy = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_minus = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_plus = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_arrow_left = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_arrow_down = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_seatmove = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_timeadd = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_mytimepack = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_period_copy = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_refresh = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_time_close = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_price = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_event = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_alert = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_help = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_fixseat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_locker = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_period_charge = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_shop = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_my_timepack_charge = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_checkbox_check = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_lock = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_menu_sign_up = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_copy = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btn_share = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_adress = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_fee = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_open_close_time = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_tel = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
